server:
  http2:
    enabled: true
  undertow:
    buffer-size: 2048
    direct-buffers: true
  port: 8080
mybatis-plus:
  mapper-locations: /mapper/*/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    url: jdbc:mysql://81.70.147.194:3336/resume?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: kdw_0517
    password: kdw_0517
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource